### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by artyprog** [Beg-in/javascripthon-loader#1]
Hello,

Thanks for Javascripthon

I got the following error on install

c:\EXP\jspy>npm install --save-dev javascripthon-loader
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> javascripthon-loader@0.1.1 postinstall c:\EXP\jspy\node_modules\javascripthon-loader
> virtualenv-postinstall

Finding virtualenv *
(node:16988) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
Unzipping https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
Creating c:\EXP\jspy\node_modules\javascripthon-loader\.node-virtualenv
Cleaning c:/EXP/jspy/node_modules/javascripthon-loader/.node-virtualenv/.node-virtualenv-sources
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn python3 ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm WARN jspy@1.0.0 No description
npm WARN jspy@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! javascripthon-loader@0.1.1 postinstall: `virtualenv-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascripthon-loader@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\xxx\sxxxx\AppData\Roaming\npm-cache\_logs\2018-07-17T06_13_36_886Z-debug.log

**Comment by chfw** [comment]
do you have python3 installed?

**Comment by artyprog** [comment]
Yes,
I have just install it on Linux and the innstall is OK
Bur I can't transpile python files

Here is my webpack config

var path = require('path')
var HtmlWebPackPlugin = require('html-webpack-plugin')

module.exports = {
    entry: './src/app.js',
    output: {
        filename: 'application.js',
        path: path.resolve(__dirname, 'dist')
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            },
            {
                test: /\.py$/,
                loader: 'javascripthon-loader'
            }
        ]
    },
    plugins: [new HtmlWebPackPlugin ({ template: 'src/index.html'})]
}

**Comment by artyprog** [comment]
backslash have been removed...

**Comment by artyprog** [comment]
and my package.json

{
  "name": "jypy",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "css-loader": "^1.0.0",
    "html-webpack-plugin": "^3.2.0",
    "javascripthon-loader": "^0.1.1",
    "style-loader": "^0.21.0",
    "webpack": "^4.16.1"
  },
  "dependencies": {
    "parcel": "^1.9.7",
    "webpack-cli": "^3.0.8"
  }
}

**Comment by chfw** [comment]
have you gotten virtualenv installed?
